openapi: 3.0.0
info:
  title: Backend API Example
  description: Backend API Example API Declaration
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: jrfisch95@gmail.com
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
- url: /api/v1

tags:
  - name: greeting
    description: Greeting APIs
  

paths:
  /hello:
    get:
      description: Returns 'Hello name/stranger!!!' to the caller
      tags:
        - greeting
      operationId: hello
      parameters:
      - name: name
        required: false
        in: query
        description: The name of a caller
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
  /goodbye:
    get:
      description: Returns 'Goodbye \<name\>!!!' to the authenticated caller
      tags:
        - greeting
      operationId: goodbye
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    HelloResponse:
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string